// libs/angular-for-react/src/app/elements/hello-world/hello-world.component.ts
import { CommonModule } from '@angular/common';
import { Component, input } from '@angular/core';

@Component({
  selector: 'ngx-hello-world',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './hello-world.component.html',
  styleUrl: './hello-world.component.scss',
})
export class HelloWorldComponent {
  name = input('World');

  getGreetingTime(): string {
    const hour = new Date().getHours();
    if (hour < 12) return 'Good morning';
    if (hour < 18) return 'Good afternoon';
    return 'Good evening';
  }
}

<div class="container">
  <h1>Hello, {{ name() }}!</h1>
  <p>
    {{ getGreetingTime() }}! This is an Angular component working as an
    Angular Element
  </p>
  <div class="stats">
    <div class="stat">
      <span class="stat-value">🅰️</span>
      <span class="stat-label">Angular</span>
    </div>
    <div class="stat">
      <span class="stat-value">⚛️</span>
      <span class="stat-label">React</span>
    </div>
    <div class="stat">
      <span class="stat-value">🎯</span>
      <span class="stat-label">Integration</span>
    </div>
  </div>
</div>

// libs/react-for-angular/src/components/react-hello-world/react-hello-world.tsx
import styles from './react-hello-world.module.scss';

interface ReactHelloWorldProps {
  name?: string;
}

export function ReactHelloWorld({ name = 'World' }: ReactHelloWorldProps) {
  const getGreetingTime = () => {
    const hour = new Date().getHours();
    if (hour < 12) return 'Good morning';
    if (hour < 18) return 'Good afternoon';
    return 'Good evening';
  };

  return (
    <div className={styles.container}>
      <h1>Hello, {name}!</h1>
      <p>
        {getGreetingTime()}! This is a React component embedded in Angular
      </p>
      <div className={styles.stats}>
        <div className={styles.stat}>
          <span className={styles.statValue}>⚛️</span>
          <span className={styles.statLabel}>React</span>
        </div>
        <div className={styles.stat}>
          <span className={styles.statValue}>🅰️</span>
          <span className={styles.statLabel}>Angular</span>
        </div>
        <div className={styles.stat}>
          <span className={styles.statValue}>🎯</span>
          <span className={styles.statLabel}>Integration</span>
        </div>
      </div>
    </div>
  );
}

export default ReactHelloWorld;
